"""Added language & description columns

Revision ID: 6c91f0c6d03f
Revises: 10045d5e9757
Create Date: 2025-02-08 18:56:30.685582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c91f0c6d03f'
down_revision: Union[str, None] = '10045d5e9757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('language', sa.String(), nullable=False))
    op.add_column('code_files', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_files', 'description')
    op.drop_column('code_files', 'language')
    # ### end Alembic commands ###
