"""Added

Revision ID: f51eb968406d
Revises: 6c91f0c6d03f
Create Date: 2025-02-08 19:48:00.590958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51eb968406d'
down_revision: Union[str, None] = '6c91f0c6d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_suggestions', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_suggestions', 'status')
    # ### end Alembic commands ###
